Code Review project
AFakhriddinov/code-review-project pull request #1
Opened 2023-02-27 12:48 UTC by AFakhriddinov

**In this milestone,**
Created a new repository
Added an html file from admissions project
Installed linters
Provided necessary comments and feedback to improve

2023-02-27 13:05 UTC, AFakhriddinov reviewed
![200w](https://user-images.githubusercontent.com/112176053/221621500-7c9a4ec8-faa3-4438-b8bb-84ac52d4c70a.gif)

You have done great in attempting this project 💯 . Your work is amazing 👍. 

**Highlights:**
- Project works properly 💯 
- Correct flow is used 💯 
- Repository is documented in a professional way 💯 

**Changes required ♻️** 
However, there is just a few to complete your work and you are almost there. Please would you mind checking the comments below

2023-02-27 13:05 UTC, AFakhriddinov commented on index.html
> +    </style>
I think it would better to use an external file for styling your web page. It will be more professional 😄  For example, you can open a new CSS file and link it to your index.html file and move all your styling code to CSS file 😃

2023-02-27 13:05 UTC, AFakhriddinov commented on index.html
> +<body>
If you use semantic tags for your page, it would look professional and meet coding standards. Please consider it. For example, you can use header for your navigation and headline while you can include your main content in article and section tags. Also, you can use include copyright information in a footer tag 😃

2023-02-27 13:05 UTC, AFakhriddinov commented on .github/workflows/linters.yml
> +name: Linters
Please kindly fix the linter error.

2023-02-27 16:48 UTC, adel-gu requested changes
# Status: Required Changes ♻️ 
**Hi @AFakhriddinov 👋🏼** 

Your review is really amazing ✨ but it can improve just a little bit 👍🏼 you still need to work on some issues but you are almost there! 💪🏼 

## Highlights
- Polite asking for changes ✔️ 
- GitHub review features are well used ✔️ 

## Required Changes ♻️

- [x] Your explanation for the **why** asking for changes is just remarkable 🥇 however it will be more efficient ✨  if you provide some examples of use cases or other resources of best practices that the student can follow to learn something 👨‍🏫😄 and don't feel that the change was unfair 👌.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 09:03 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @AFakhriddinov 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-03-04 04:33 UTC, merged